import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import {Hero} from "@/components/hero/hero";
import {Header} from "@/components/header/header";
import {About} from "@/components/about/about";
import {Footer} from "@/components/footer/footer";
import {Investments} from "@/components/investments/investments";
import {News} from "@/components/news/news";

export default function Home() {
  return (
    <>
      <Head>
        <title>KlubApril2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <Header />
        <Hero />
        <About />
        <News />
        <Investments />
        <Footer />
      </main>
    </>
  )
}
